### ISSUE TITLE
Small Request :)

### ISSUE THREAD

**Issue by ShidMD** [Manodiestra/open-pokemmo-bot#1]
Hey, can you point me the data structure for the connection with the official server?

I was thinking of doing some kind of pokkemo logger, to extract data from the game (encounters locations, safari rates, etc..) since there is no official source from changes on the original games, and i'm a lazy computer guy, so no taking notes everytime xD

Btw, are you spanish?
Ty in advance.

**Comment by ShidMD** [comment]
Oh, sorry, i just read your code, didn't before the request 😢 
Thought your bot replaced the client...

**Comment by Manodiestra** [comment]
@ShidMD Yeah, my code just uses screen shots to grab info from the game and creates kayboard and mouse user inputs. Good luck on your project and thanks for closing the issue.
